[tool.poetry]
name = "NAME"
version = "0.0.1"
description = ""
authors = ["Jonathan Ballet <jon@multani.info>"]

[tool.poetry.dependencies]
python = "^3.12"
structlog = "24.2.0"

[tool.poetry.group.dev.dependencies]
black = "24.4.2"
isort = "5.13.2"
mypy = "1.10.1"
pytest = "8.0.2"
pytest-asyncio = "0.23.5.post1"
pytest-black = "0.3.12"
pytest-cov = "5.0.0"
pytest-isort = "4.0.0"
pytest-mypy = "0.10.3"
ruff = "0.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
# script = "NAME.cli:app"

[tool.pytest.ini_options]
asyncio_mode = "auto"
addopts = """
--doctest-modules
--isort
--black
--cov-branch
--cov-report html
--cov-report term
--tb short
--verbose
--verbose
--mypy

--cov NAME
"""
#--mypy
filterwarnings = [
    "ignore:<class 'pytest_black.BlackItem'> is not using a cooperative constructor.*:pytest.PytestDeprecationWarning",
    "ignore:.*argument to BlackItem is deprecated.*:pytest.PytestRemovedIn8Warning",
    "ignore:BlackItem is an Item subclass.*:pytest.PytestWarning",
]

testpaths = [
    "NAME",
    "tests",
]

[tool.isort]
profile = "black"
use_parentheses = false
force_single_line = true

[tool.mypy]
packages = ["NAME"]
