name: Python

on:
  push:
    branches:
      - "**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Test Python

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: poetry

      - name: Build
        run: poetry install

      - name: Test
        run: poetry run pytest
