name: Python

on:
  push:
    branches:
      - "**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Test Python

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Build
        run: uv sync --all-extras --dev

      - name: Test
        run: make check

  docker:
    runs-on: ubuntu-latest
    name: Test Docker build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker build
        run: docker build .
